name: neginteb workflow

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Ensure persian_datetime_picker compatibility
        run: |
          flutter pub add persian_datetime_picker:^3.1.1 || true

      - name: Clean & get packages
        run: |
          flutter clean
          flutter pub get

      - name: Run codegen
        run: flutter pub run build_runner build --delete-conflicting-outputs || true

      - name: Build web
        run: flutter build web

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      # Use ssh-agent action to load the private key from secrets (safer/reliable)
      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}

      # Optional diagnostic: detect the header of the private key (shows key format only)
      - name: Detect SSH private key header (diagnostic, safe)
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        run: |
          # print only the first line of the key (like "-----BEGIN OPENSSH PRIVATE KEY-----")
          echo "---- key header (for diagnostics) ----"
          echo "${SSH_PRIVATE_KEY}" | sed -n '1p'
          echo "--------------------------------------"

      - name: Add server to known_hosts (save fingerprint)
        env:
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${SSH_PORT} -H ${SSH_HOST} >> ~/.ssh/known_hosts 2>/dev/null || true
          cat ~/.ssh/known_hosts

      - name: Update base href in index.html
        env:
          WEBSITE_URL: ${{ secrets.WEBSITE_URL }}
        run: |
          sed -i "s|href=\"/\"|href=\"${WEBSITE_URL}\"|g" build/web/index.html

      - name: Deploy to server (scp)
        env:
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_PATH: ${{ secrets.SERVER_REMOTE_PATH }}
        run: |
          # Use scp (ssh-agent has already loaded the key)
          echo "Starting deploy to ${SSH_HOST}:${REMOTE_PATH} (port ${SSH_PORT})"
          scp -o StrictHostKeyChecking=yes -P ${SSH_PORT} -r build/web/* ${SSH_USERNAME}@${SSH_HOST}:${REMOTE_PATH}/
